[package]
name = "commitfmt-cc"
version = "0.0.0"
publish = false
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
build = "build.rs"

[dependencies]
memchr = { workspace = true }
nom = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
build-deps = { workspace = true }
serde_derive = { workspace = true }
tempfile = { workspace = true }
test-generator = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }

[lints]
workspace = true
