[package]
name = "commitfmt-git"
version = "0.0.0"
publish = false
authors = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
documentation = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[dependencies]
strum = { workspace = true, features = ["derive", "strum_macros"] }
tempfile = { workspace = true, optional = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[features]
testing = ["dep:tempfile"]

[lints]
workspace = true
