name: NPM publish

on:
  workflow_call:
    inputs:
      plan:
        required: true
        type: string

jobs:
  publish:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v4
      - name: Fetch artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: artifacts-*
          path: target/distrib/
          merge-multiple: true
      - name: Unpack artifacts
        run: |
          cd target/distrib
          find . -maxdepth 1 -type f -name "*.tar.xz" -exec tar -xJf {} \;
          find . -maxdepth 1 -type f -name "*.zip" -exec \
            sh -c 'dir="${1%.zip}"; \
            mkdir -p "$dir" && unzip -o "$1" -d "$dir"' _ {} \;
          cd ../..
      - name: Print artifacts
        run: ls target/distrib
