name: Quality Assurance

on:
  push:

jobs:
  test:
    name: Tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: taiki-e/install-action@nextest
      - run: cargo nextest run --all-features

  code-style:
    name: Code style check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy
      - name: Check formatting
        run: cargo fmt --all --check
      - name: Check clippy
        run: cargo clippy
